In [1]:
import face_recognition
import cv2
import numpy as np

In [2]:
# Loading all the images
img_hrithik1 = face_recognition.load_image_file('imagedetec/Hrithik-Roshan-1.jpg') #train image #returns an array representation of images
img_hrithik1 = cv2.cvtColor(img_hrithik1, cv2.COLOR_BGR2RGB) # BGR TO RGB
img_hrithik2 = face_recognition.load_image_file('imagedetec/Hrithik-Roshan-2.jpg') # test image
img_hrithik2 = cv2.cvtColor(img_hrithik2, cv2.COLOR_BGR2RGB)
img_ratantata = face_recognition.load_image_file('imagedetec/Ratan_tata.jpg') # Other image
img_ratantata = cv2.cvtColor(img_ratantata, cv2.COLOR_BGR2RGB)

In [3]:
img_hrithik1.shape, img_hrithik2.shape, img_ratantata.shape

((563, 750, 3), (485, 728, 3), (702, 512, 3))

In [4]:
# locating face location in train image
face_loc = face_recognition.face_locations(img_hrithik1)[0]
hrithik_encod = face_recognition.face_encodings(img_hrithik1)[0]

In [5]:
face_loc, hrithik_encod

((142, 527, 409, 260),
 array([-9.82032418e-02,  1.23916805e-01,  1.01674996e-01, -8.27004910e-02,
        -1.20795101e-01,  8.33639130e-03, -4.58095968e-02, -7.79753923e-02,
         1.03093952e-01,  1.98765658e-04,  1.34342775e-01, -1.38080642e-02,
        -2.72528946e-01,  9.58857387e-02, -2.18442157e-02,  6.77506626e-02,
        -1.95460230e-01, -1.07855462e-01, -9.78895202e-02, -4.80119623e-02,
        -1.48690585e-02,  1.01422735e-01, -1.38067054e-02,  5.22496700e-02,
        -6.71409667e-02, -2.95457691e-01, -7.72568956e-02, -1.03088774e-01,
         9.85174924e-02, -5.06266281e-02,  1.43722845e-02, -1.65149178e-02,
        -2.32358575e-01, -8.34491476e-02,  1.13417497e-02, -4.48134169e-03,
        -3.40195708e-02, -6.65993616e-02,  1.91092476e-01,  2.03121938e-02,
        -8.79732892e-02,  2.89051477e-02,  1.34244606e-01,  2.94710666e-01,
         9.52666923e-02,  1.12161301e-01,  3.34046185e-02,  2.84326635e-03,
         8.04169029e-02, -2.46345416e-01,  1.38993889e-01,  1.029

In [6]:
# Since we have now the face location coordinates of train image lets draw a rectangle around them using opencv
cv2.rectangle(img_hrithik1,(face_loc[3],face_loc[0]),(face_loc[1],face_loc[2]),(0,255,0),3)

array([[[155, 138, 129],
        [155, 138, 129],
        [155, 138, 129],
        ...,
        [163, 158, 157],
        [163, 158, 157],
        [163, 158, 157]],

       [[154, 137, 128],
        [154, 137, 128],
        [154, 137, 128],
        ...,
        [163, 158, 157],
        [163, 158, 157],
        [163, 158, 157]],

       [[153, 136, 127],
        [153, 136, 127],
        [154, 137, 128],
        ...,
        [163, 158, 157],
        [163, 158, 157],
        [163, 158, 157]],

       ...,

       [[ 97,  71,  64],
        [ 94,  68,  61],
        [ 84,  61,  53],
        ...,
        [194, 176, 165],
        [194, 176, 165],
        [194, 176, 165]],

       [[ 81,  57,  51],
        [ 81,  57,  51],
        [ 76,  54,  48],
        ...,
        [194, 176, 165],
        [194, 176, 165],
        [194, 176, 165]],

       [[ 70,  46,  40],
        [ 73,  49,  43],
        [ 72,  50,  44],
        ...,
        [194, 176, 165],
        [194, 176, 165],
        [194, 176, 165]]

In [7]:
# locating face location, encoding the test image then putting the rectangle arounf the face location in test image
test_loc = face_recognition.face_locations(img_hrithik2)[0]
test_encod = face_recognition.face_encodings(img_hrithik2)[0]
cv2.rectangle(img_hrithik2,(test_loc[3],test_loc[0]),(test_loc[1],test_loc[2]),(0,255,0),3)

array([[[183, 167, 161],
        [188, 169, 164],
        [189, 170, 165],
        ...,
        [155, 142, 140],
        [153, 141, 137],
        [152, 140, 136]],

       [[193, 174, 169],
        [196, 177, 172],
        [197, 177, 172],
        ...,
        [152, 139, 137],
        [151, 138, 136],
        [149, 136, 134]],

       [[186, 166, 161],
        [190, 170, 165],
        [193, 173, 168],
        ...,
        [151, 137, 138],
        [149, 135, 136],
        [148, 134, 135]],

       ...,

       [[ 97,  89,  90],
        [ 96,  88,  89],
        [ 96,  88,  89],
        ...,
        [121, 115, 116],
        [115, 109, 110],
        [112, 106, 107]],

       [[ 97,  89,  90],
        [ 97,  89,  90],
        [ 96,  88,  89],
        ...,
        [ 16,  10,  11],
        [ 12,   7,   8],
        [ 11,   6,   7]],

       [[ 97,  89,  90],
        [ 97,  89,  90],
        [ 97,  89,  90],
        ...,
        [ 27,  22,  23],
        [ 27,  25,  25],
        [ 29,  27,  27]]

# Step 3 - Comparing the faces using their encodings

In [8]:
results = face_recognition.compare_faces([hrithik_encod], test_encod)

# Checking the face distance to see the similarities
facedis = face_recognition.face_distance([hrithik_encod], test_encod)

In [9]:
results, facedis

([True], array([0.42884762]))

In [10]:
# Putting the results on the required images using opencv
cv2.putText(img_hrithik2, str(results)+'  '+str(round(facedis[0],2)), (100,100), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 3)

array([[[183, 167, 161],
        [188, 169, 164],
        [189, 170, 165],
        ...,
        [155, 142, 140],
        [153, 141, 137],
        [152, 140, 136]],

       [[193, 174, 169],
        [196, 177, 172],
        [197, 177, 172],
        ...,
        [152, 139, 137],
        [151, 138, 136],
        [149, 136, 134]],

       [[186, 166, 161],
        [190, 170, 165],
        [193, 173, 168],
        ...,
        [151, 137, 138],
        [149, 135, 136],
        [148, 134, 135]],

       ...,

       [[ 97,  89,  90],
        [ 96,  88,  89],
        [ 96,  88,  89],
        ...,
        [121, 115, 116],
        [115, 109, 110],
        [112, 106, 107]],

       [[ 97,  89,  90],
        [ 97,  89,  90],
        [ 96,  88,  89],
        ...,
        [ 16,  10,  11],
        [ 12,   7,   8],
        [ 11,   6,   7]],

       [[ 97,  89,  90],
        [ 97,  89,  90],
        [ 97,  89,  90],
        ...,
        [ 27,  22,  23],
        [ 27,  25,  25],
        [ 29,  27,  27]]

In [11]:
# viewing the images using opencv
cv2.imshow('1',img_hrithik1)
cv2.imshow('2',img_hrithik2)
cv2.imshow('3',img_ratantata)

cv2.waitKey(0) #always remember to include it when using cv2.imshow to view the iamges

-1